version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    command: "python -m backend"
    container_name: reddit_wrapper_webapp_backend
    ports:
      - "8787:8787"
    environment:
      - CORS_ORIGINS=http://0.0.0.0:8080
    healthcheck:
      test: curl -fk http://0.0.0.0:8787/docs || exit 1
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    command: "python -m http.server 8080 -d frontend/"
    volumes:
      - ./frontend/src:/project/frontend
    container_name: reddit_wrapper_webapp_frontend
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile
      target: node_base
    command: "npm run build:css"
    volumes:
      - ./frontend/:/frontend
    container_name: reddit_wrapper_webapp_tailwind
    depends_on:
      backend:
        condition: service_healthy
    stdin_open: true
